ALTER TABLE tasks ADD COLUMN folder TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN freezes_used INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN freeze_month TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN growth INTEGER NOT NULL DEFAULT 100;
ALTER TABLE users ADD COLUMN tutorial_done INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN music_track INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN music_volume INTEGER NOT NULL DEFAULT 35;
ALTER TABLE users ADD COLUMN is_admin INTEGER NOT NULL DEFAULT 0;
